### ISSUE TITLE
声卡声音不正常

### ISSUE THREAD

**Issue by zengxiaoliang** [Leif160519/Dell-OptiPlex-3050-EFI#4]
系统信息
版本：10.13.6 (17G65)
LIlu:1.2.5
VoodooHDA.kext   2.8.9

现象
前置耳机接口能听到声音，但不清晰，犹如伴唱

升级过VoodooHDA 和lilu 到最新版本，发现无法驱动

**Comment by Leif160519** [comment]
伴唱的话是不是你耳机没插好导致的呢
无法驱动的话可以更换我提供的EFI-2试试看

**Comment by zengxiaoliang** [comment]
其他-音频MIDI   拖动下声道分贝值，正常了
